services:

  solr:
    image: solr:9.8.1
    container_name: solr
    ports:
      - "8983:8983"
    environment:
      - SOLR_JAVA_MEM=-Xms512m -Xmx1g
    volumes:
      - solr_data:/var/solr
      - ./web.xml:/opt/solr/server/solr-webapp/webapp/WEB-INF/web.xml
    command: >
      bash -c "
        solr start -cloud -f
        -Dsolr.jetty.request.header.size=65536
        -Dsolr.jetty.filter.allowOrigins=*
        -Dsolr.jetty.filter.allowedMethods=GET,POST,OPTIONS,HEAD
      "
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8983/solr/admin/collections?action=CLUSTERSTATUS" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  solr-init:
    image: curlimages/curl:latest
    container_name: solr-init
    labels:
      - "org.springframework.boot.ignore=true"
    depends_on:
      solr:
        condition: service_healthy
    volumes:
      - ./data:/data
    entrypoint: ["sh", "/data/solr-init.sh"]

  cors-checker:
    image: curlimages/curl:latest
    container_name: cors-checker
    labels:
      - "org.springframework.boot.ignore=true"
    depends_on:
      solr-init:
        condition: service_started
    volumes:
      - ./data:/data
    entrypoint: ["sh", "/data/solr-cors.sh"]

  wiremock:
    image: wiremock/wiremock:3.12.1
    container_name: wiremock-holdings
    ports:
      - "18089:8080"
    volumes:
      - ./wiremock:/home/wiremock

  redis:
    image: 'redis/redis-stack:7.4.0-v8'
    labels:
      - "org.springframework.boot.service-connection=redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  redis-insight:
    image: 'redis/redisinsight:latest'
    ports:
      - '5540:5540'
    volumes:
      - redis_insight_data:/data
    depends_on:
      redis:
        condition: service_healthy

volumes:
  solr_data:
  redis_data:
  redis_insight_data:
