# https://docs.spring.io/spring-ai/reference/api/chat/comparison.html
spring:
  autoconfigure:
    exclude:
      - org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration
  ai:
    model:
      chat: openai

    # https://platform.openai.com/login?next=%2Fapi-keys
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        model: llama-3.3-70b-versatile